/* Публичные сведения: исходная карта libraries-map.html, публикации mk.lpr-reg.ru.
   Координаты на этой демонстрационной карте привязаны к населённым пунктам, не к входам зданий. */
(() => {
  'use strict';
  const source = 'https://mk.lpr-reg.ru';
  // Проверенные публикации Министерства культуры ЛНР, дата проверки — сентябрь 2026.
  const editorialEvents = [
    {id:'costumes',title:'«Нарядное путешествие: четыре региона, одна история»',kind:'Выставка',category:'exhibition',city:'Луганск',venue:'Луганский республиканский центр народного творчества, ул. Ленина, 36',start:'2026-09-29',end:'2026-09-29',time:'13:30',badge:'29 сентября · 13:30',description:'Открытие выставки 30 кукол в традиционных костюмах четырёх регионов. Срок работы выставки в публикации не указан.',image:`${source}/uploads/posts/2026-09/1790083560_afisha-kukly-sodruzhestva.jpg`,url:`${source}/14184-v-luganske-otkroetsja-vystavka-narjadnoe-puteshestvie-chetyre-regiona-odna-istorija.html`,age:null,free:null},
    {id:'shmorel',title:'«Александр Шморель — студент, патриот, антифашист, святой»',kind:'Выставка',category:'exhibition',city:'Краснодон',venue:'Музей «Молодая гвардия»',start:'2026-09-22',end:'2026-11-15',time:null,badge:'До 15 ноября',description:'История подпольной группы «Белая роза» и молодёжного Сопротивления. По сообщению министерства, вход свободный; часы работы уточняйте в музее.',image:`${source}/uploads/posts/2026-09/1790083032_img_20260922_150329.jpg`,url:`${source}/14183-v-muzee-molodaja-gvardija-otkrylas-vystavka-aleksandr-shmorel-student-patriot-antifashist-svjatoj.html`,age:null,free:true},
    {id:'dal',title:'«Тайны русского слова: По следам В. И. Даля»',kind:'Онлайн-марафон',category:'online',city:'Онлайн',venue:'Луганский республиканский центр народного творчества',start:'2026-09-23',end:'2026-10-31',time:null,badge:'Заявки до 31 октября',description:'Приглашаются театральные коллективы, студии и чтецы. Формат участия — видео 3–5 минут; условия и форма заявки размещены у организатора.',image:`${source}/uploads/posts/2026-09/1790162414_afisha-dal.jpg`,url:`${source}/14188-luganskij-centr-narodnogo-tvorchestva-zapuskaet-onlajn-marafon-k-225-letiju-vladimira-dalja.html`,age:null,free:null}
  ];
  const todayISO = () => new Date().toLocaleDateString('sv-SE');
  const eventActive = event => event.end >= todayISO();
  function eventCards(items){return items.map(event=>`<article class="event-card"><div class="event-photo"><img src="${esc(event.image)}" alt="${esc(event.kind)}: ${esc(event.title)}" loading="lazy"><span class="event-badge">${eventActive(event)?esc(event.badge):'Архив · 2026'}</span></div><div class="event-info"><span class="event-kind">${esc(event.kind.toUpperCase())} · ${esc(event.city.toUpperCase())}</span><h3>${esc(event.title)}</h3><p>${esc(event.description)}</p><span class="event-place">◎ ${esc(event.venue)}</span><a class="event-action" href="${esc(event.url)}" target="_blank" rel="noopener noreferrer">Подробности у организатора ↗</a></div></article>`).join('');}
  function renderHomeEvents(){const active=editorialEvents.filter(eventActive);$('home-events').innerHTML=eventCards(active.length?active:editorialEvents);}
  function renderEventScreen(){
    const day=$('event-date')?.value||'',kind=$('event-kind')?.value||'',city=$('event-city')?.value||'';
    const matched=editorialEvents.filter(event=>(!day||(day>=event.start&&day<=event.end))&&(!kind||kind===event.category)&&(!city||city===event.city));
    $('event-screen-grid').innerHTML=matched.length?eventCards(matched):'<div class="panel empty-state"><strong>На выбранную дату анонсов нет</strong>Попробуйте изменить фильтры. Отсутствие анонса не означает, что учреждение закрыто.</div>';
  }
  const categories = {
    library: { label: 'Библиотеки', one: 'Библиотека', color: '#53846e', icon: '▤' },
    museum: { label: 'Музеи', one: 'Музей', color: '#b77953', icon: '◆' },
    art: { label: 'Школы искусств', one: 'Школа искусств', color: '#9281a9', icon: '✳' },
    culture: { label: 'Дома культуры', one: 'Дом культуры', color: '#d6a358', icon: '✦' },
    leisure: { label: 'Культурно-досуговые центры', one: 'Культурно-досуговый центр', color: '#669b9c', icon: '✺' },
    theatre: { label: 'Театры', one: 'Театр', color: '#a66368', icon: '◈' },
    cinema: { label: 'Кинотеатры', one: 'Кинотеатр', color: '#7874a3', icon: '▣' },
    concert: { label: 'Концертные организации', one: 'Концертная организация', color: '#9c7799', icon: '♫' },
    exhibition: { label: 'Выставочные залы', one: 'Выставочный зал', color: '#a78456', icon: '▧' },
    education: { label: 'Дополнительное образование', one: 'Учреждение дополнительного образования', color: '#7e9a63', icon: '✎' },
    archive: { label: 'Архивы', one: 'Архив', color: '#879078', icon: '▥' },
    historic: { label: 'Историко-культурные объекты', one: 'Историко-культурный объект', color: '#9e795b', icon: '⌘' },
    monument: { label: 'Памятники', one: 'Памятник истории и культуры', color: '#976e55', icon: '♜' },
    folk: { label: 'Народное творчество', one: 'Объект народного творчества', color: '#b18a66', icon: '✿' },
    literary: { label: 'Литературные места', one: 'Литературный объект', color: '#748f80', icon: '❞' },
    tourism: { label: 'Культурный туризм', one: 'Туристический объект культурного наследия', color: '#699298', icon: '⌁' }
  };
  const places = [
    { id:'slavyanoserbsk',type:'library',city:'Славяносербск',lat:48.6972,lng:38.9812,name:'Славяносербская центральная библиотека',short:'Современное пространство для чтения и общения',description:'Первое модельное пространство округа: обновлённые залы, цифровой доступ к Национальной электронной библиотеке и среда для читателей всех возрастов.',tags:['Семейное чтение','Электронная библиотека','Событийный зал'],audience:['family','children','youth'],photo:`${source}/uploads/posts/2026-09/1789713559_img-20260916-124039.jpg`,url:`${source}/14168-v-slavjanoserbske-otkrylas-pervaja-modelnaja-biblioteka.html`,updated:'2026-09-16' },
    { id:'antratsit',type:'library',city:'Антрацит',lat:48.1151,lng:39.0913,name:'Креативная семейная библиотека',short:'Место, где интересно всей семье',description:'Малая модельная библиотека с зонами информации и релаксации, семейного общения, абонементом «Почитай и поиграй» и интерактивной площадкой.',tags:['Семейный досуг','Чтение','Детям'],audience:['family','children'],photo:null,updated:'2026-07-08'},
    { id:'belovodsk',type:'library',city:'Беловодск',lat:49.209,lng:39.588,name:'Беловодская модельная библиотека',short:'Книги и новые возможности',description:'Модельная библиотека Беловодска — пространство для чтения и культурно-просветительских встреч.',tags:['Чтение','Образование'],audience:['family','children','youth'],updated:'2025-12-26'},
    { id:'perevalsk',type:'library',city:'Перевальск',lat:48.438,lng:38.844,name:'Перевальская модельная библиотека',short:'Пространство для читателей всех возрастов',description:'Модельная библиотека в Перевальске. Дополнительную информацию об учреждении уточняйте в официальных источниках.',tags:['Чтение','Семья'],audience:['family','children'],updated:'2025-12-04'},
    { id:'stakhanov',type:'library',city:'Стаханов',lat:48.568,lng:38.65,name:'Модельная библиотека Стаханова',short:'Современная библиотека города',description:'Модельное библиотечное пространство Стаханова. Адрес и режим работы уточняйте в учреждении.',tags:['Чтение','Образование'],audience:['family','youth'],updated:'2024-12-26'},
    { id:'stakhanov-museum',type:'museum',city:'Стаханов',lat:48.5705,lng:38.653,name:'Городской историко-художественный музей г. Стаханова',short:'История города и декоративно-прикладное искусство',description:'Музей получил пять передвижных и семь стационарных витрин. Оборудование используется в экспозициях об истории стахановского движения и декоративно-прикладном искусстве советской эпохи.',tags:['История','Искусство','Экспозиции'],audience:['family','children','youth'],photo:`${source}/uploads/posts/2025-10/1759743273_photo_2025-10-06_12-06-35.jpg`,url:`${source}/12486-tehnicheskoe-obnovlenie-muzeja-stahanova-novye-vozmozhnosti-dlja-kulturnogo-razvitija.html`,updated:'2025-10-06'},
    { id:'antratsit-museum',type:'museum',city:'Антрацит',lat:48.119,lng:39.087,name:'Антрацитовский исторический музей',short:'История края в новых экспозициях',description:'Для музея закуплены витрины, пресс-волы, звуковое оборудование, микрофоны и манекены. После оснащения открылся обновлённый экспозиционный зал.',tags:['Краеведение','Выставки','История'],audience:['family','children','youth'],photo:`${source}/uploads/posts/2025-10/1759828196_photo_2025-10-06_13-10-59.jpg`,url:`${source}/12491-antracitovskij-istoricheskij-muzej-sovremennoe-osnaschenie-vklad-v-sohranenie-pamjati.html`,updated:'2025-10-07'},
    { id:'alchevsk-museum',type:'museum',city:'Алчевск',lat:48.474,lng:38.797,name:'Алчевский городской исторический музей',short:'Обновлённые экспозиционные залы',description:'В музее капитально отремонтированы входная группа, коммуникации и помещения. Учреждение получило новые витрины, стенды и оборудование; открыты два обновлённых зала.',tags:['История','Выставки','Доступная среда'],audience:['family','children','youth'],accessible:true,photo:`${source}/uploads/posts/2026-09/1789713826_img-20260917-111139.jpg`,url:`${source}/14169-v-alchevskom-muzee-posle-remonta-otkrylis-dva-obnovlennyh-jekspozicionnyh-zala.html`,updated:'2026-09-17'},
    { id:'kirovsk-museum',type:'museum',city:'Кировск',lat:48.637,lng:38.643,name:'Кировский историко-художественный музей',short:'Экспозиция «Город на линии фронта»',description:'Для новой экспозиции поставлены музейный комплекс и витрины. Ремонт здания продолжается; перед визитом уточните режим работы.',tags:['История','Выставки'],audience:['family','youth'],photo:`${source}/uploads/posts/2025-08/1755156899_photo_2025-08-14_10-01-14.jpg`,url:`${source}/12207-v-kirovskom-istoriko-hudozhestvennom-muzee-prodolzhajutsja-raboty-v-ramkah-nacproekta-semja.html`,updated:'2025-08-14'},
    { id:'perevalsk-museum',type:'museum',city:'Перевальск',lat:48.4405,lng:38.847,name:'Перевальский районный исторический музей',short:'История района в обновлённом здании',description:'В здании обновлены инженерные системы, освещение и помещения. Созданы доступный санузел и гардероб.',tags:['Краеведение','История','Доступная среда'],audience:['family','children'],accessible:true,photo:`${source}/uploads/posts/2025-08/1754900564_photo_2025-08-11_11-15-15.jpg`,url:`${source}/12186-perevalskij-rajonnyj-istoricheskij-muzej-posetila-ministr-kultury-rf-olga-borisovna-ljubimova.html`,updated:'2025-08-11'},
    { id:'belovodsk-museum',type:'museum',city:'Беловодск',lat:49.211,lng:39.591,name:'Беловодский краеведческий музей',short:'Новая жизнь краеведческого музея',description:'После капитального ремонта обновлены помещения и коммуникации. Музей получил современные экспозиционные витрины и вновь открылся 5 марта 2026 года.',tags:['Краеведение','История','Выставки'],audience:['family','children','youth'],photo:`${source}/uploads/posts/2026-03/1772718516_photo_2026-03-05_16-46-32.jpg`,url:`${source}/13217-v-belovodske-posle-kapitalnogo-remonta-torzhestvenno-otkrylsja-obnovlennyj-kraevedcheskij-muzej.html`,updated:'2026-03-05'},
    { id:'chervona-art',type:'art',city:'Червоная Поляна',lat:48.239,lng:39.0963,name:'Червонополянская детская школа искусств',short:'Пять творческих коллективов и юные таланты',description:'Школа вошла в число лучших сельских учреждений культуры по итогам отбора на 2027 год. Педагоги и воспитанники участвуют в творческих конкурсах.',tags:['Детям','Творчество','Образование'],audience:['children','family','youth'],url:`${source}/13917-objavleny-pobediteli-konkursa-na-denezhnoe-pooschrenie-luchshih-selskih-uchrezhdenij-kultury-lnr-v-2027-godu.html`,updated:'2026-07-09'},
    { id:'dyakovo-art',type:'art',city:'Дьяково',lat:47.9437,lng:39.1285,name:'Дьяковская детская музыкальная школа',short:'Музыкальное образование и народные традиции',description:'Школа признана победителем отбора лучших сельских учреждений культуры на 2027 год. Педагоги сохраняют народные музыкальные традиции.',tags:['Музыка','Детям','Традиции'],audience:['children','family','youth'],url:`${source}/13917-objavleny-pobediteli-konkursa-na-denezhnoe-pooschrenie-luchshih-selskih-uchrezhdenij-kultury-lnr-v-2027-godu.html`,updated:'2026-07-09'},
    { id:'maloivanovka',type:'culture',city:'Малоивановка',lat:48.3766,lng:38.6454,name:'Малоивановский Дом культуры',short:'Казачья песня и сельское творчество',description:'Филиал Перевальского районного Дворца культуры. Здесь проводят фестиваль казачьей песни; работают вокальный, танцевальный и литературный коллективы.',tags:['Фестивали','Народное творчество','Для семьи'],audience:['family','children','youth'],url:`${source}/13917-objavleny-pobediteli-konkursa-na-denezhnoe-pooschrenie-luchshih-selskih-uchrezhdenij-kultury-lnr-v-2027-godu.html`,updated:'2026-07-09'},
    { id:'orekhovo',type:'culture',city:'Орехово',lat:48.0436,lng:39.1724,name:'Клуб села Орехово',short:'Творчество и активный досуг для молодёжи',description:'Филиал Антрацитовского ДК им. Ленина. При клубе работают творческие и спортивные объединения, а также коллектив художественного слова «Юность».',tags:['Молодёжи','Творчество','Клуб'],audience:['youth','children','family'],url:`${source}/13917-objavleny-pobediteli-konkursa-na-denezhnoe-pooschrenie-luchshih-selskih-uchrezhdenij-kultury-lnr-v-2027-godu.html`,updated:'2026-07-09'}
  ];
  const $ = (id) => document.getElementById(id);
  const esc = (value) => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const stored = (key, fallback) => { try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } };
  const state = { type:'all',city:'',audience:'',access:'',data:'',distance:'',query:'',heritage:false,view:'map',selected:null,coords:null,mapReady:false,favorites:new Set(stored('culture-favorites-v2',[])),savedRoutes:stored('culture-routes-v2',[]),route:[],travel:'walk',routePreset:'',listMode:false };
  const mapCommand = (action, values={}) => { if(action==='data'||state.mapReady) $('map').contentWindow?.postMessage({cultureMap:'command',action,...values},'*'); };
  const mapType = item => {
    if(item.type !== 'winner')return item.type;
    if(/школ/i.test(item.name))return 'art';
    if(/музе/i.test(item.name))return 'museum';
    return 'culture';
  };
  function syncCatalog(message){
    if(!Array.isArray(message.places))return;
    (message.categories||[]).forEach(c=>{if(c.id!=='winner'&&!categories[c.id])categories[c.id]={label:c.label,one:c.singular||c.label,color:'#668b7b',icon:'✳'}});
    const incoming=message.places.filter(p=>p && typeof p.id==='string' && Array.isArray(p.coords) && p.coords.length===2).map(item=>{
      const type=mapType(item);
      const tags=Array.isArray(item.features)?item.features:[];
      const isChild=/детск|школ|семейн/i.test([item.name,...tags].join(' '));
      const photo=(item.photos||[]).find(url=>typeof url==='string'&&/^https?:\/\//.test(url))||null;
      return {id:item.id,type,city:item.city||'Не указан',lat:Number(item.coords[0]),lng:Number(item.coords[1]),name:item.name,
        short:item.concept||categories[type]?.one||'Культурный объект',description:item.description||item.concept||'Описание не добавлено.',
        tags,audience:isChild?['family','children','youth']:['family','youth'],accessible:tags.some(t=>/доступн/i.test(t)),
        photo,url:item.article||'',updated:null,address:item.address||'',hours:item.hours||'',contacts:item.contacts||'',timing:item.timing||'',status:item.status||''};
    }).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lng));
    places.splice(0,places.length,...incoming);
    $('hero-place-count').textContent=places.length;
    $('hero-city-count').textContent=new Set(places.map(p=>p.city)).size;
    state.mapReady=true;
    const select=$('city-filter');select.innerHTML='<option value="">Все населённые пункты</option>';
    [...new Set(places.map(p=>p.city))].sort((a,b)=>a.localeCompare(b,'ru')).forEach(city=>{const option=document.createElement('option');option.value=city;option.textContent=city;select.append(option)});
    if(state.city&&!Array.from(select.options).some(o=>o.value===state.city))state.city='';
    select.value=state.city;
    renderFilters();renderResults();
    if(state.view!=='map')renderScreen(state.view);
    if(location.hash.startsWith('#place=')){try{openDetail(decodeURIComponent(location.hash.slice(7)))}catch{}}
  }
  window.addEventListener('message',event=>{
    if(event.source!==$('map').contentWindow)return;
    if(event.data?.cultureMap==='data')syncCatalog(event.data);
    if(event.data?.cultureMap==='select' && typeof event.data.id==='string')openDetail(event.data.id);
  });
  $('map').addEventListener('load',()=>mapCommand('data'));
  let toastTimeout;
  const notify = (message) => { $('toast').textContent=message; $('toast').classList.add('show'); clearTimeout(toastTimeout); toastTimeout=setTimeout(()=>$('toast').classList.remove('show'),3500); };
  const distance = (a,b) => { const r=Math.PI/180,dLat=(b.lat-a.lat)*r,dLng=(b.lng-a.lng)*r; const h=Math.sin(dLat/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin(dLng/2)**2; return 12742*Math.asin(Math.sqrt(h)); };
  const matching = () => {
    const q=state.query.toLocaleLowerCase('ru').trim();
    const keywords = q.replace(/рядом|сегодня|детские|мероприятия|пушкинская карта/g,'').trim();
    return places.filter(p => {
      if(state.type!=='all' && p.type!==state.type)return false;
      if(state.heritage && p.type!=='museum')return false;
      if(state.city && p.city!==state.city)return false;
      if(state.audience && !p.audience.includes(state.audience))return false;
      if(state.access && !p.accessible)return false;
      if(state.data==='photo' && !p.photo)return false;
      if(state.data==='source' && !p.url)return false;
      if(state.distance && state.coords && distance(state.coords,p)>Number(state.distance))return false;
      if(q.includes('пушкинск') || q.includes('концерт') || q.includes('мероприяти') || q.includes('сегодня'))return false; // отсутствуют подтверждённые сведения
      if(q.includes('детск') && !p.audience.includes('children'))return false;
      if(keywords && ![p.name,p.city,p.short,p.description,categories[p.type].label,...p.tags].join(' ').toLocaleLowerCase('ru').includes(keywords))return false;
      return true;
    }).sort((a,b) => state.coords ? distance(state.coords,a)-distance(state.coords,b) : a.name.localeCompare(b.name,'ru'));
  };
  const media = (p, cls='') => p.photo ? `<img class="${cls}" src="${esc(p.photo)}" alt="${esc(p.name)}" loading="lazy" onerror="this.replaceWith(Object.assign(document.createElement('div'),{className:'result-placeholder',textContent:'✳'}))">` : `<div class="result-placeholder ${cls}" aria-label="Фотография не добавлена">✳</div>`;
  function renderFilters(){ $('quick-filters').innerHTML=`<button class="chip ${state.type==='all'?'active':''}" data-type="all">Все места</button>`+Object.entries(categories).map(([key,c])=>`<button class="chip ${state.type===key?'active':''}" data-type="${key}">${c.icon} &nbsp;${c.label}</button>`).join(''); }
  function renderResults(){
    const found=matching(); $('result-title').textContent=state.heritage?'Музеи и история':state.type==='all'?'Все места':categories[state.type].label;
    $('result-count').textContent=`· ${found.length}`;$('map-visible-count').textContent=`${found.length} мест на карте`;
    $('results').innerHTML=found.length?found.map(p=>`<article class="result-card ${state.selected===p.id?'active':''}" data-id="${esc(p.id)}" tabindex="0" role="button" aria-label="Открыть ${esc(p.name)}">${media(p)}<div class="result-body"><div class="result-type"><i style="--accent:${categories[p.type].color}"></i>${categories[p.type].one} · ${esc(p.city)}</div><h3>${esc(p.name)}</h3><p>${esc(state.coords?`${distance(state.coords,p).toFixed(1)} км · `:'')}${esc(p.short)}</p></div><span class="result-arrow">↗</span></article>`).join(''):`<div class="empty-state"><strong>Ничего не найдено</strong>Попробуйте изменить запрос или фильтры.<br>Подтверждённых событий и данных о Пушкинской карте пока нет.</div>`;
    renderMarkers(found);
  }
  function renderMarkers(found){mapCommand('filter',{ids:found.map(p=>p.id)});}
  function fitMap(){mapCommand('fit',{ids:matching().map(p=>p.id)});}
  function openDetail(id){const p=places.find(x=>x.id===id);if(!p)return;state.selected=id;renderResults();const favorite=state.favorites.has(id);$('detail-content').innerHTML=`<div class="detail-hero">${p.photo?`<img src="${esc(p.photo)}" alt="${esc(p.name)}" onerror="this.replaceWith(Object.assign(document.createElement('div'),{className:'no-photo',textContent:'✳'}))">`:'<div class="no-photo">✳</div>'}</div><div class="detail-padding"><div class="detail-kicker">${categories[p.type].one} · ${esc(p.city)}</div><h2>${esc(p.name)}</h2><div class="detail-address">◎ ${esc(p.city)} · координаты населённого пункта: ${p.lat.toFixed(4)}, ${p.lng.toFixed(4)}</div><p class="detail-desc">${esc(p.description)}</p><div class="detail-actions"><button class="primary" data-action="route" data-id="${p.id}">↗ &nbsp; Построить маршрут</button><button class="${favorite?'saved':''}" data-action="favorite" data-id="${p.id}">${favorite?'♥ В избранном':'♡ В избранное'}</button><button data-action="events" data-id="${p.id}">▦ &nbsp; Мероприятия</button><button data-action="share" data-id="${p.id}">↗ &nbsp; Поделиться</button>${p.phone?`<a href="tel:${esc(p.phone)}">Позвонить</a>`:'<button disabled title="Телефон пока не указан">Позвонить · нет данных</button>'}${p.site?`<a href="${esc(p.site)}" target="_blank" rel="noopener noreferrer">Перейти на сайт ↗</a>`:'<button disabled title="Сайт пока не указан">Сайт · нет данных</button>'}</div><div class="detail-section"><h3>Об объекте</h3><div class="detail-row"><span>Тип</span><b>${categories[p.type].one}</b></div><div class="detail-row"><span>Населённый пункт</span><b>${esc(p.city)}</b></div><div class="detail-row"><span>Обновлено</span><b>${new Date(p.updated+'T12:00:00').toLocaleDateString('ru-RU')}</b></div><div class="detail-row"><span>Доступность</span><b>${p.accessible?'Есть сведения о доступной среде':'Сведения не указаны'}</b></div><div class="detail-row"><span>Афиша</span><b>Нет подтверждённых событий</b></div></div><div class="detail-section"><h3>Направления</h3><div class="detail-tags">${p.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div></div>${p.url?`<div class="detail-section"><h3>Источник</h3><a href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">Официальная публикация ↗</a></div>`:''}<div class="detail-section"><h3>Нашли неточность?</h3><p>Сообщите, какие сведения нужно проверить. В демонстрационной версии обращение сохраняется в этом браузере.</p><button class="button button-dark" data-action="report" data-id="${p.id}">Сообщить об ошибке</button></div><p class="source-disclaimer">Адрес, телефон, сайт, часы работы и условия посещения не подтверждены в исходных данных. Перед визитом уточните информацию в учреждении. Метка поставлена по населённому пункту.</p></div>`;
    const suggest=document.createElement('a'); suggest.href=`index.html?place=${encodeURIComponent(p.name+' · '+p.city)}#suggest-scenario`; suggest.textContent='✳  Предложить постановку об этом месте ↗'; $('detail-content').querySelector('.detail-actions').append(suggest);
    if(p.address)$('detail-content').querySelector('.detail-address').textContent=`◎ ${p.address}`;
    const details=$('detail-content').querySelector('.detail-section');
    const updatedRow=[...details.querySelectorAll('.detail-row')].find(row=>row.querySelector('span')?.textContent==='Обновлено');
    if(updatedRow && !p.updated)updatedRow.querySelector('b').textContent='Дата не указана в источнике';
    if(p.hours)details.insertAdjacentHTML('beforeend',`<div class="detail-row"><span>Режим работы</span><b>${esc(p.hours)}</b></div>`);
    if(p.timing)details.insertAdjacentHTML('beforeend',`<div class="detail-row"><span>Дата / срок</span><b>${esc(p.timing)}</b></div>`);
    if(p.contacts)details.insertAdjacentHTML('beforeend',`<div class="detail-row"><span>Контакты из источника</span><b>${esc(p.contacts)}</b></div>`);
    $('drawer-backdrop').hidden=false;$('detail-drawer').classList.add('open');$('detail-drawer').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';history.replaceState(null,'',`#place=${encodeURIComponent(id)}`);mapCommand('select',{id});$('drawer-close').focus();
  }
  function closeDetail(){if(!$('detail-drawer').classList.contains('open'))return;$('detail-drawer').classList.remove('open');$('detail-drawer').setAttribute('aria-hidden','true');$('drawer-backdrop').hidden=true;document.body.style.overflow='';state.selected=null;renderResults();if(location.hash.startsWith('#place='))history.replaceState(null,'',location.pathname+location.search);}
  function toggleFavorite(id){state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);localStorage.setItem('culture-favorites-v2',JSON.stringify([...state.favorites]));$('fav-count').textContent=state.favorites.size;if(state.selected===id)openDetail(id);notify(state.favorites.has(id)?'Добавлено в «Мою культуру»':'Удалено из избранного');if(state.view==='favorites')renderScreen('favorites');}
  function geo(){if(!navigator.geolocation){notify('Геолокация недоступна в этом браузере');return}notify('Определяем ваше местоположение…');navigator.geolocation.getCurrentPosition(pos=>{state.coords={lat:pos.coords.latitude,lng:pos.coords.longitude};mapCommand('locate',{coords:[state.coords.lat,state.coords.lng]});const nearest=[...places].sort((a,b)=>distance(state.coords,a)-distance(state.coords,b)).slice(0,3);$('near-results').hidden=false;$('near-results').innerHTML='<strong>Ближайшие места в подборке</strong>'+nearest.map(p=>`<button data-place="${p.id}">${esc(p.name)} <span>${distance(state.coords,p).toFixed(1)} км ↗</span></button>`).join('');renderResults();notify('Ближайшие объекты показаны первыми');showMap();},()=>notify('Не удалось определить местоположение. Разрешите доступ в настройках браузера.'),{enableHighAccuracy:false,timeout:10000});}
  function showMap(){switchView('map');$('explore').scrollIntoView({behavior:'smooth'});setTimeout(()=>mapCommand('resize'),300);}
  const pathTo = p => `https://yandex.ru/maps/?rtext=${state.coords?`${state.coords.lat},${state.coords.lng}`:''}~${p.lat},${p.lng}&rtt=${state.travel==='car'?'auto':state.travel==='transit'?'mt':'pd'}`;
  function routeTo(id){const p=places.find(x=>x.id===id);if(!p)return;closeDetail();state.route=[id];state.routePreset='';switchView('routes');}
  function routeOrder(ids){const remaining=ids.map(id=>places.find(p=>p.id===id)).filter(Boolean),ordered=[];let current=state.coords||{lat:48.574,lng:39.308};while(remaining.length){remaining.sort((a,b)=>distance(current,a)-distance(current,b));const next=remaining.shift();ordered.push(next);current=next;}return ordered;}
  function renderRoutes(){const ordered=routeOrder(state.route);const km=ordered.reduce((total,p,i)=>total+distance(i?ordered[i-1]:(state.coords||{lat:48.574,lng:39.308}),p),0);const speeds={walk:4.5,car:40,transit:22};let opts=`<div class="section-kicker">ПЛАНИРУЙТЕ ВПЕЧАТЛЕНИЯ ✳</div><h2>Культурные маршруты</h2><p class="screen-intro">Соберите свою прогулку или выберите готовую подборку. Расстояние рассчитано по прямой от вашей геопозиции, а если она неизвестна — от центра Луганска. Реальный путь смотрите в навигаторе.</p><div class="panel"><h3>Выберите идею для прогулки</h3><div class="route-options">${[['museum','Музейный маршрут'],['family','Семейный маршрут'],['weekend','Маршрут выходного дня'],['literary','Литературный маршрут']].map(([k,l])=>`<button data-preset-route="${k}" class="${state.routePreset===k?'active':''}">${l}</button>`).join('')}</div><p>Маршруты формируются из объектов, представленных в каталоге. Для литературного маршрута подтверждённых точек пока нет.</p></div><div class="panel"><h3>Мой маршрут</h3><div class="screen-toolbar"><select id="route-add"><option value="">Добавить объект...</option>${places.filter(p=>!state.route.includes(p.id)).map(p=>`<option value="${p.id}">${esc(p.name)} · ${esc(p.city)}</option>`).join('')}</select><button class="button button-dark" id="route-add-button">+ Добавить</button></div><div class="route-options">${[['walk','Пешком'],['car','На машине'],['transit','Общественный транспорт']].map(([k,l])=>`<button data-travel="${k}" class="${state.travel===k?'active':''}">${l}</button>`).join('')}</div>${ordered.length?`<ol class="route-list">${ordered.map(p=>`<li><button data-place="${p.id}">${esc(p.name)}</button> <button data-remove="${p.id}" aria-label="Убрать ${esc(p.name)}">×</button></li>`).join('')}</ol><div class="route-stats">Примерно ${km.toFixed(1)} км по прямой · около ${Math.round(km/speeds[state.travel]*60)} мин без учёта остановок. Для общественного транспорта время особенно приблизительно.</div><div class="route-options"><a class="button button-dark" target="_blank" rel="noopener noreferrer" href="${pathTo(ordered[0])}">Открыть первый участок в навигаторе ↗</a><button id="route-save">♡ Сохранить маршрут</button><button id="route-clear">Очистить</button></div>`:'<div class="empty-state">Добавьте место или выберите готовую подборку.</div>'}</div>`;return opts;}
  function renderAnalytics(){const cities=[...new Set(places.map(p=>p.city))].sort((a,b)=>a.localeCompare(b,'ru'));const counts=Object.entries(categories).map(([k,v])=>[v.label,places.filter(p=>p.type===k).length]);const max=Math.max(...counts.map(x=>x[1]));return `<div class="section-kicker">КУЛЬТУРНАЯ ИНФРАСТРУКТУРА ✳</div><h2>Регион в цифрах</h2><p class="screen-intro">Обзор только по опубликованной подборке этой демонстрационной карты, а не по всем учреждениям ЛНР. Для управленческой аналитики потребуется полная проверенная база объектов и численность населения.</p><div class="analytics-grid"><div class="analytics-stat"><b>${places.length}</b><span>объектов в подборке</span></div><div class="analytics-stat"><b>${cities.length}</b><span>населённых пунктов</span></div><div class="analytics-stat"><b>${Object.keys(categories).length}</b><span>типов объектов</span></div><div class="analytics-stat"><b>${places.filter(p=>!p.photo).length}</b><span>без фотографий</span></div></div><div class="panel"><h3>Объекты по типам</h3><div class="bars">${counts.map(([label,count])=>`<div class="bar-row"><span>${label}</span><div class="bar-track"><i style="width:${count/max*100}%"></i></div><b>${count}</b></div>`).join('')}</div></div><div class="panel"><h3>Культурный паспорт населённого пункта</h3><p>Выберите населённый пункт, чтобы увидеть объекты, которые есть в текущей подборке.</p><div class="municipality-grid">${cities.map(city=>`<button data-city="${esc(city)}">${esc(city)}<span>${places.filter(p=>p.city===city).length} ↗</span></button>`).join('')}</div></div><div class="panel"><h3>Актуальность сведений</h3><p>Без фотографий: ${places.filter(p=>!p.photo).length} · Без ссылок на источники: ${places.filter(p=>!p.url).length} · Обновлены более года назад: ${places.filter(p=>Date.now()-new Date(p.updated).getTime()>365*86400000).length}.</p><button class="button button-dark" id="download-csv">Скачать каталог CSV ↗</button></div><p class="notice">Информация требует актуализации, если не обновлялась больше года. Отсутствующие поля не считаются подтверждёнными данными. Показатели охвата населения и посещаемости станут доступны после подключения статистических источников.</p>`;}
  function renderScreen(view){const content=$('screen-content');if(view==='routes')content.innerHTML=renderRoutes();if(view==='analytics'){
      content.innerHTML=renderAnalytics().replace(/Обновлены более года назад: \d+/,`Без даты обновления: ${places.filter(p=>!p.updated).length}`);
      content.querySelectorAll('.bar-row').forEach(row=>{if(row.querySelector('b')?.textContent==='0')row.remove()});
      content.querySelectorAll('.analytics-stat')[2].querySelector('b').textContent=new Set(places.map(p=>p.type)).size;
    }if(view==='events'){
      content.innerHTML=`<div class="section-kicker">КУЛЬТУРНЫЙ КАЛЕНДАРЬ ✳</div><h2>Афиша и культурные события</h2><p class="screen-intro">Подтверждённые анонсы Министерства культуры ЛНР. Для выставок указаны опубликованные сроки, для открытия — точная дата; стоимость и возраст отмечены только там, где их сообщил организатор.</p><div class="screen-toolbar"><label class="event-filter-label">Дата <input id="event-date" type="date" aria-label="Дата мероприятия"></label><label class="event-filter-label">Формат <select id="event-kind" aria-label="Формат мероприятия"><option value="">Все форматы</option><option value="exhibition">Выставки</option><option value="online">Онлайн</option></select></label><label class="event-filter-label">Где <select id="event-city" aria-label="Место мероприятия"><option value="">Все места</option><option value="Луганск">Луганск</option><option value="Краснодон">Краснодон</option><option value="Онлайн">Онлайн</option></select></label></div><div class="event-grid" id="event-screen-grid"></div><p class="event-disclaimer">Анонсы не обновляются автоматически. Перед поездкой проверьте актуальность события и режим работы по ссылке на публикацию министерства.</p>`;
      renderEventScreen();
    }
    if(view==='favorites'){const chosen=places.filter(p=>state.favorites.has(p.id));content.innerHTML=`<div class="section-kicker">ЛИЧНОЕ ПРОСТРАНСТВО ✳</div><h2>Моя культура</h2><p class="screen-intro">Сохранённые места и маршруты доступны в этом браузере.</p>${chosen.length?`<div class="screen-cards">${chosen.map(p=>`<button class="screen-card" data-place="${p.id}">${p.photo?`<img src="${esc(p.photo)}" alt="" loading="lazy">`:'<div class="card-fallback">✳</div>'}<div class="screen-card-body"><small>${categories[p.type].one} · ${esc(p.city)}</small><h3>${esc(p.name)}</h3><p>Открыть карточку ↗</p></div></button>`).join('')}</div>`:'<div class="panel empty-state"><strong>Пока нет избранных мест</strong>Нажмите ♡ в карточке объекта, чтобы сохранить его здесь.</div>'}<div class="panel" style="margin-top:20px"><h3>Мои маршруты</h3>${state.savedRoutes.length?state.savedRoutes.map((r,i)=>`<div class="detail-row"><span>${esc(r.name)}</span><button data-saved-route="${i}">Открыть ↗</button></div>`).join(''):'<p>Сохранённых маршрутов пока нет.</p>'}</div>`;}
  }
  function switchView(view){closeDetail();state.view=view;document.querySelectorAll('.nav-link').forEach(el=>el.classList.toggle('active',el.dataset.view===view));$('screen-view').hidden=view==='map';$('home').hidden=view!=='map';if(view!=='map')renderScreen(view);window.scrollTo({top:0,behavior:'smooth'});if(view==='map')setTimeout(()=>mapCommand('resize'),100);}
  function downloadCsv(){const columns=['id','name','type','city','lat','lng','description','updated','source'];const rows=places.map(p=>[p.id,p.name,categories[p.type].label,p.city,p.lat,p.lng,p.description,p.updated||'',p.url||'']);const csv='\ufeff'+[columns,...rows].map(row=>row.map(x=>`"${String(x).replace(/"/g,'""')}"`).join(';')).join('\r\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='culture-map-lnr.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
  document.addEventListener('click',async e=>{
    const target=e.target.closest('[data-view],[data-type],[data-id],[data-place],[data-action],[data-preset],[data-city],[data-preset-route],[data-travel],[data-remove],[data-saved-route]');if(!target)return;
    if(target.dataset.view){switchView(target.dataset.view);return}
    if(target.dataset.type){state.type=target.dataset.type;state.heritage=false;$('map-layer').classList.remove('active');renderFilters();renderResults();fitMap();return}
    if(target.dataset.preset){state.type=target.dataset.preset==='heritage'?'museum':'all';state.audience=target.dataset.preset==='heritage'?'':target.dataset.preset;$('audience-filter').value=state.audience;state.heritage=target.dataset.preset==='heritage';$('map-layer').classList.toggle('active',state.heritage);renderFilters();renderResults();showMap();fitMap();return}
    if(target.dataset.city){state.city=target.dataset.city;$('city-filter').value=state.city;showMap();renderResults();fitMap();return}
    if(target.dataset.id && !target.dataset.action){openDetail(target.dataset.id);return}
    if(target.dataset.place){openDetail(target.dataset.place);return}
    if(target.dataset.presetRoute){const preset=target.dataset.presetRoute;state.routePreset=preset;state.route=preset==='museum'?['stakhanov-museum','alchevsk-museum','perevalsk-museum']:preset==='family'?['antratsit','antratsit-museum','orekhovo']:preset==='weekend'?['slavyanoserbsk','stakhanov-museum','alchevsk-museum']:[];renderScreen('routes');if(!state.route.length)notify('Для этого маршрута пока нет подтверждённых объектов');return}
    if(target.dataset.travel){state.travel=target.dataset.travel;renderScreen('routes');return}
    if(target.dataset.remove){state.route=state.route.filter(id=>id!==target.dataset.remove);renderScreen('routes');return}
    if(target.dataset.savedRoute!==undefined){state.route=[...state.savedRoutes[Number(target.dataset.savedRoute)].ids];state.routePreset='';switchView('routes');return}
    if(target.dataset.action){const id=target.dataset.id,p=places.find(x=>x.id===id);if(target.dataset.action==='favorite')toggleFavorite(id);if(target.dataset.action==='route')routeTo(id);if(target.dataset.action==='events'){closeDetail();switchView('events')}if(target.dataset.action==='share'){const url=`${location.origin}${location.pathname}#place=${encodeURIComponent(id)}`;try{if(navigator.share)await navigator.share({title:p.name,url});else{await navigator.clipboard.writeText(url);notify('Ссылка скопирована')}}catch{notify('Ссылка: '+url)}}if(target.dataset.action==='report'){const message=prompt('Что нужно исправить в карточке?');if(message?.trim()){const reports=stored('culture-reports-v2',[]);reports.push({id,message:message.trim().slice(0,1000),date:new Date().toISOString(),status:'pending'});localStorage.setItem('culture-reports-v2',JSON.stringify(reports));notify('Обращение сохранено в этом браузере (демоверсия).')}}}
  });
  $('results').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.classList.contains('result-card')){e.preventDefault();openDetail(e.target.dataset.id)}});
  $('search').addEventListener('input',e=>{state.query=e.target.value;renderResults();fitMap()});
  $('filter-toggle').addEventListener('click',()=>{const hidden=!$('advanced-filters').hidden;$('advanced-filters').hidden=hidden;$('filter-toggle').setAttribute('aria-expanded',String(!hidden));$('filter-toggle').classList.toggle('selected',!hidden)});
  ['city','audience','access','data','distance'].forEach(k=>$(k+'-filter').addEventListener('change',e=>{if(k==='distance'&&e.target.value&&!state.coords){e.target.value='';notify('Сначала определите местоположение');geo();return}state[k]=e.target.value;renderResults();fitMap()}));
  $('reset-filters').addEventListener('click',()=>{Object.assign(state,{type:'all',city:'',audience:'',access:'',data:'',distance:'',query:'',heritage:false});$('search').value='';['city','audience','access','data','distance'].forEach(k=>$(k+'-filter').value='');$('map-layer').classList.remove('active');renderFilters();renderResults();fitMap()});
  $('list-toggle').addEventListener('click',()=>{state.listMode=!state.listMode;$('list-toggle').classList.toggle('active',state.listMode);$('list-toggle').setAttribute('aria-pressed',String(state.listMode));document.querySelector('.explore-layout').classList.toggle('list-mode',state.listMode);if(innerWidth<=760&&state.listMode)$('results').scrollIntoView({behavior:'smooth',block:'start'});if(!state.listMode)setTimeout(()=>mapCommand('resize'),100)});
  $('map-layer').addEventListener('click',()=>{state.heritage=!state.heritage;state.type='all';$('map-layer').classList.toggle('active',state.heritage);$('map-layer').setAttribute('aria-pressed',String(state.heritage));renderFilters();renderResults();fitMap();if(state.heritage)notify('Показаны музеи. Подтверждённых памятников в подборке пока нет.')});
  $('map-fit').addEventListener('click',fitMap);$('map-locate').addEventListener('click',geo);$('hero-near').addEventListener('click',geo);$('near-locate').addEventListener('click',geo);$('hero-explore').addEventListener('click',showMap);$('favorites-nav').addEventListener('click',()=>switchView('favorites'));$('about-button').addEventListener('click',()=>switchView('analytics'));$('screen-back').addEventListener('click',showMap);$('drawer-close').addEventListener('click',closeDetail);$('drawer-backdrop').addEventListener('click',closeDetail);
  document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDetail()});
  $('screen-content').addEventListener('click',e=>{if(e.target.closest('#download-csv'))downloadCsv();if(e.target.closest('#route-add-button')){const id=$('route-add').value;if(id&&!state.route.includes(id)){state.route.push(id);renderScreen('routes')}}if(e.target.closest('#route-save')){if(!state.route.length)return;const name=prompt('Название маршрута:','Мой культурный маршрут');if(name?.trim()){state.savedRoutes.push({name:name.trim().slice(0,100),ids:[...state.route]});localStorage.setItem('culture-routes-v2',JSON.stringify(state.savedRoutes));notify('Маршрут сохранён в «Моей культуре»')}}if(e.target.closest('#route-clear')){state.route=[];state.routePreset='';renderScreen('routes')}});
  $('screen-content').addEventListener('change',e=>{if(e.target.matches('#event-date,#event-kind,#event-city'))renderEventScreen()});
  [...new Set(places.map(p=>p.city))].sort((a,b)=>a.localeCompare(b,'ru')).forEach(city=>{const option=document.createElement('option');option.value=city;option.textContent=city;$('city-filter').append(option)});
  $('fav-count').textContent=state.favorites.size;renderFilters();renderResults();renderHomeEvents();
  // После загрузки iframe исходная карта передаёт весь актуальный каталог, включая локальные изменения.
})();
